#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

from waflib import Logs
import os

top = '.'

def options(opt):
	# stub
	return

def configure(conf):
	# check for dedicated server build
	if conf.options.DEDICATED:
		return

	if conf.options.SUPPORT_BSP2_FORMAT:
		conf.env.append_unique('DEFINES', 'SUPPORT_BSP2_FORMAT')

	conf.env.append_unique('DEFINES', 'REF_DLL')

def build(bld):
	libs = [ 'engine_includes' ]
	# on PSVita do not link any libraries that are already in the main executable, but add the includes target
	if bld.env.DEST_OS == 'psvita':
		libs += [ 'sdk_includes' ]
	else:
		libs += [ 'public', 'M' ]

	if bld.env.DEDICATED:
		return

	library = 'cshlib'
	source = bld.path.ant_glob(['*.c'])

	if bld.env.DEST_OS == 'amiga':
		library = 'cprogram'
		bld.env.POSTFIX = ".so"
		source += bld.path.parent.ant_glob([
			'os_specific/amiga/main.c'
		])
	else:
		bld.env.POSTFIX = ""

	features = ['c', library]

	bld(target = 'ref_soft' + bld.env.POSTFIX,
		features = features,
		source   = source,
		includes = '.',
		use      = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
